import React, { PureComponent } from 'react'
import log_render_time from '../hoc/log_render_time'

export class ProductList extends PureComponent {
  render() {
    return (
      <div>
        <h1>ProductList</h1>
        <ul>
          <li>fweqw1</li>
          <li>fweqw2</li>
          <li>fweqw3</li>
          <li>fweqw4</li>
          <li>fweqw5</li>
          <li>fweqw6</li>
          <li>fweqw7</li>
          <li>fweqw8</li>
          <li>fweqw9</li>
          <li>fweqw10</li>
          <li>fweqw11</li>
          <li>fweqw12</li>
          <li>fweqw13</li>
          <li>fweqw14</li>
          <li>fweqw15</li>
          <li>fweqw16</li>
          <li>fweqw17</li>
          <li>fweqw18</li>
          <li>fweqw19</li>
          <li>fweqw20</li>
          <li>fweqw21</li>
          <li>fweqw22</li>
          <li>fweqw23</li>
          <li>fweqw24</li>
          <li>fweqw25</li>
          <li>fweqw26</li>
          <li>fweqw27</li>
          <li>fweqw28</li>
          <li>fweqw29</li>
          <li>fweqw30</li>
          <li>fweqw31</li>
          <li>fweqw32</li>
          <li>fweqw33</li>
          <li>fweqw34</li>
          <li>fweqw35</li>
          <li>fweqw36</li>
          <li>fweqw37</li>
          <li>fweqw38</li>
          <li>fweqw39</li>
          <li>fweqw40</li>
          <li>fweqw41</li>
          <li>fweqw42</li>
          <li>fweqw43</li>
          <li>fweqw44</li>
          <li>fweqw45</li>
          <li>fweqw46</li>
          <li>fweqw47</li>
          <li>fweqw48</li>
          <li>fweqw49</li>
          <li>fweqw50</li>
          <li>fweqw51</li>
          <li>fweqw52</li>
          <li>fweqw53</li>
          <li>fweqw54</li>
          <li>fweqw55</li>
          <li>fweqw56</li>
          <li>fweqw57</li>
          <li>fweqw58</li>
          <li>fweqw59</li>
          <li>fweqw60</li>
          <li>fweqw61</li>
          <li>fweqw62</li>
          <li>fweqw63</li>
          <li>fweqw64</li>
          <li>fweqw65</li>
          <li>fweqw66</li>
          <li>fweqw67</li>
          <li>fweqw68</li>
          <li>fweqw69</li>
          <li>fweqw70</li>
          <li>fweqw71</li>
          <li>fweqw72</li>
          <li>fweqw73</li>
          <li>fweqw74</li>
          <li>fweqw75</li>
          <li>fweqw76</li>
          <li>fweqw77</li>
          <li>fweqw78</li>
          <li>fweqw79</li>
          <li>fweqw80</li>
          <li>fweqw81</li>
          <li>fweqw82</li>
          <li>fweqw83</li>
          <li>fweqw84</li>
          <li>fweqw85</li>
          <li>fweqw86</li>
          <li>fweqw87</li>
          <li>fweqw88</li>
          <li>fweqw89</li>
          <li>fweqw90</li>
          <li>fweqw91</li>
          <li>fweqw92</li>
          <li>fweqw93</li>
          <li>fweqw94</li>
          <li>fweqw95</li>
          <li>fweqw96</li>
          <li>fweqw97</li>
          <li>fweqw98</li>
          <li>fweqw99</li>
          <li>fweqw100</li>
        </ul>
      </div>
    )
  }
}

export default log_render_time(ProductList)